### ISSUE TITLE
Reimporting the same file creates new tasks

### ISSUE THREAD

**Issue by danboh** [braini75/msproject_import#11]
Hello,

Thanks again for this plugin!

Is there any way you can update existing tasks when reimporting the same file instead of just creating new tasks?

Thanks!

**Comment by braini75** [comment]
I will check this.

**Comment by ytalokaio** [comment]
Very good Task

**Comment by Abigail27** [comment]
Hello,

Is there any update regarding on this issue?

Thanks!
