### ISSUE TITLE
ArgumentError (undefined class/module MsprojResource)

### ISSUE THREAD

**Issue by jojomach2012** [braini75/msproject_import#15]
Hi Thomas,

I am trying to use your plugin, but it is impossible for me to be able to import my data and I can not understand and correct the bug.

This is what I get in the logs:

Have you ever encountered such problems? If yes, how to fix it plz?

I thank you in advance.

Have a good day

![capture](https://cloud.githubusercontent.com/assets/25202541/22068389/2ac673f4-dd95-11e6-8bc2-ac554b9e36db.PNG)

**Comment by braini75** [comment]
Which Project Version are you using?

**Comment by jojomach2012** [comment]
I use the latest version of the plugin present on the git. I downloaded it at the beginning of the week only, I had no problems during the installation.

**Comment by braini75** [comment]
Sorry, I mean which version of MS Project ;)

**Comment by jojomach2012** [comment]
Ah sorry, it's MS Project 2010. I seen on the documentation's plugin that it supports 2007 or later no ?

**Comment by jojomach2012** [comment]
At times, I do not get the same error that I just presented.

I found myself with an ActiveRecord: RecordNotFound error, I modified in the plugin code the search for an issue with root_id = 0 because actually in my database I do not have records with this value for the attribute root_id But root_id = 1 should be able to find the corresponding record.

![image](https://cloud.githubusercontent.com/assets/25202541/22108697/a772e756-de54-11e6-9968-aec473023531.png)

**Comment by jojomach2012** [comment]
It's the same with original code

![image](https://cloud.githubusercontent.com/assets/25202541/22108872/7a3950bc-de55-11e6-97b9-32725448715f.png)

**Comment by braini75** [comment]
I think I've found the issue. Does your redmine Server has a /tmp Directory writable for the user of the http-Service of redmine. What OS is redmine running at?

**Comment by braini75** [comment]
Please try my new Version.

**Comment by jojomach2012** [comment]
OS : RHEL6 - Linux
I have the /tmp directory writable by my user of the http-Service. I can found on it the /msproj_imp created by the plugin with files on multiple directories.

Ok I will try it, thanks

**Comment by jojomach2012** [comment]
I have the same problem : 

On production.log : 
![image](https://cloud.githubusercontent.com/assets/25202541/22241379/664c16b6-e21f-11e6-83c4-df75556a8593.png)


On the webapp : 
![image](https://cloud.githubusercontent.com/assets/25202541/22241401/74292fc6-e21f-11e6-9549-38cf32bc6e12.png)

**Comment by jojomach2012** [comment]
I managed to find a solution to correct the problem but I do not understand the principle. In my log file, I see that it looks for an Issue with id = 0 (WHERE Issues.root_id = 0). So I'm going directly into my database to place a record with its values. What is the purpose of searching for an issue with the primary key id = 0? Why do we need it? Recordings starting at 1, how can one place a corresponding record in this case?

**Comment by braini75** [comment]
I probably found the Problem!
Maybe you forgot to **load default configuration data** ('Step 7 - Database default data set' in [https://redmine.org/projects/redmine/wiki/RedmineInstall](https://redmine.org/projects/redmine/wiki/RedmineInstall)):
`RAILS_ENV=production bundle exec rake redmine:load_default_data`
 Please retry with a clean Installation!
