### ISSUE TITLE
Massive MSProject Import

### ISSUE THREAD

**Issue by shawndibble** [braini75/msproject_import#3]
I have a large MS project XML file (20 mb) with just shy of 10k issues. Unfortunately I have to cut this down to about 2 mb each and import them as the large file is just too much for redmine to handle at once. This creates a separate parent MS project import issue for each import.

Is there a better way to perform such a large import?

**Comment by braini75** [comment]
My biggest Project so far is 3289kB. That was making no trouble.
There is a way to read a XML-File line by line, but that is a different approach and not very easy to implement. What does the log (/log/production.log) says, where the problem is

**Comment by shawndibble** [comment]
Sorry about not updating this. Didn't even get an email from your reply. I was able to figure out it was a timeout issue.
