### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by mrhatch** [braini75/msproject_import#5]
I am using:
Redmine version                3.1.1.stable
  Ruby version                   2.0.0-p647 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem  
Redmine plugins:
  msproject_import               0.2.0

from the bitnami stack, when I try an import I receive the following errors:

Started POST "/msproject_import/analyze?project_id=fy-15-icarc-support" for 192.168.0.115 at 2015-10-08 17:27:33 +0000
Processing by MsprojImpController#analyze as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ouEGlMwQv+u3P6noGQ6hPQOqhlnht0Sjhlc3yULtyF5oBTqCCPIcHaHGssAXzrLrZ33weHQBTfelX5IzdPMEOg==", "uploaded_file"=>#<ActionDispatch::Http::UploadedFile:0x007f9ab579fc78 @tempfile=#<Tempfile:/tmp/RackMultipart20151008-8026-19n6llr.xml>, @original_filename="icarc.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"icarc.xml\"\r\nContent-Type: text/xml\r\n">, "commit"=>"Analyze", "project_id"=>"fy-15-icarc-support"}
  Current user: mike (id=5)
upload xml file: ActionDispatch::Http::UploadedFile: #<ActionDispatch::Http::UploadedFile:0x007f9ab579fc78 @tempfile=#<Tempfile:/tmp/RackMultipart20151008-8026-19n6llr.xml>, @original_filename="icarc.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"icarc.xml\"\r\nContent-Type: text/xml\r\n"> : icarc.xml : uploaded_path: /tmp/RackMultipart20151008-8026-19n6llr.xml
Completed 500 Internal Server Error in 2630ms (ActiveRecord: 1.0ms)

TypeError (no implicit conversion of nil into String):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by mrhatch** [comment]
I went in and made sure that all of the fields in the xml had a value, there were a few that didn't like manager etc.  I am now getting a slightly different error:

Started GET "/msproject_import/upload?project_id=fy-15-icarc-support" for 127.0.0.1 at 2015-10-08 17:40:49 +0000
Processing by MsprojImpController#upload as HTML
  Parameters: {"project_id"=>"fy-15-icarc-support"}
  Current user: mike (id=5)
  Rendered plugins/msproject_import/app/views/msproj_imp/upload.html.erb within layouts/base (1.7ms)
Completed 200 OK in 93ms (Views: 43.7ms | ActiveRecord: 41.1ms)
Started POST "/msproject_import/analyze?project_id=fy-15-icarc-support" for 127.0.0.1 at 2015-10-08 17:40:54 +0000
Processing by MsprojImpController#analyze as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"mNQQNrYBpI//560FbsKius/KjZqJwUzlxuzdC3sgYeyAe6QBRRTyOSnvR0oekC0seVLJhUJjQ5eA0g3lD1gg3Q==", "uploaded_file"=>#<ActionDispatch::Http::UploadedFile:0x007f9ab62ba7e8 @tempfile=#<Tempfile:/tmp/RackMultipart20151008-8026-75lxk1.xml>, @original_filename="Test.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"Test.xml\"\r\nContent-Type: text/xml\r\n">, "commit"=>"Analyze", "project_id"=>"fy-15-icarc-support"}
  Current user: mike (id=5)
upload xml file: ActionDispatch::Http::UploadedFile: #<ActionDispatch::Http::UploadedFile:0x007f9ab62ba7e8 @tempfile=#<Tempfile:/tmp/RackMultipart20151008-8026-75lxk1.xml>, @original_filename="Test.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"Test.xml\"\r\nContent-Type: text/xml\r\n"> : Test.xml : uploaded_path: /tmp/RackMultipart20151008-8026-75lxk1.xml
Completed 500 Internal Server Error in 910ms (ActiveRecord: 2.9ms)

**Comment by mrhatch** [comment]
Not sure how I closed this.  I have found the line with the error but I am not sure how to fix it.  The problem is in ms_proj_imp_controller and the error occurs on this line:

@tasks.push(xml_tasks child)

I am not familiar enough with Ruby to get past that error.

**Comment by braini75** [comment]
Can you provide some Information about the MS Project Version you are using to create the XML-files? Would it be possible to send me such a XML-file?

**Comment by mrhatch** [comment]
The file I was using was actually generated by ProjectLibre which purports to write files in the Project XML format.  I generated one from another tool and it worked so the problem is likely with ProjectLibre.  For some reason I can't attach the file, I will send it via email and see if that works.

**Comment by mrhatch** [comment]
Here is a copy of the XML I was trying.  It is generated by ProjectLibre on
Redhat.

**Comment by braini75** [comment]
Please try the new Version, if this Problem still exist.

**Comment by blackisle51** [comment]
I have the same issue - opened an .mpp file in Libreproject; Exported as MS Project xml; run the import and receive:

Processing by MsprojImpController#analyze as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"qa2W9BVtuZmoY/WfMI3T/rOQrFVP3hBiR8jbT/mG4eAkPesZnNm+xmWj2ZWLZNZqcTbQNAU8J3bOgEcrF/ftDw==", "uploaded_file"=>#<ActionDispatch::Http::UploadedFile:0x007efd2fde1c40 @tempfile=#<Tempfile:/tmp/RackMultipart20160603-17101-vq955k.xml>, @original_filename="AFRC 20160602.mpp.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"AFRC 20160602.mpp.xml\"\r\nContent-Type: text/xml\r\n">, "commit"=>"Analyze", "details"=>"1", "project_id"=>"afrc"}
  Current user: admin (id=1)
upload xml file: ActionDispatch::Http::UploadedFile: #<ActionDispatch::Http::UploadedFile:0x007efd2fde1c40 @tempfile=#<Tempfile:/tmp/RackMultipart20160603-17101-vq955k.xml>, @original_filename="AFRC 20160602.mpp.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"uploaded_file\"; filename=\"AFRC 20160602.mpp.xml\"\r\nContent-Type: text/xml\r\n"> : AFRC 20160602.mpp.xml : uploaded_path: /tmp/RackMultipart20160603-17101-vq955k.xml
Completed 500 Internal Server Error in 8812ms (ActiveRecord: 59.8ms)

TypeError (no implicit conversion of nil into String):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem  
Redmine plugins:
  msproject_import               0.4.0

**Comment by blackisle51** [comment]
Just exported using MS Project 365 - the import of this xml file worked without issue. I guess this is possibly a LibreProject issue.
