### ISSUE TITLE
Error: ["Assignee can't be blank"]

### ISSUE THREAD

**Issue by donalby** [braini75/msproject_import#8]
Getting this error on my redmine setup. 
Redmine on bitnami stack, version 
Environment:
  Redmine version                2.5.2.stable
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
MS Project 2013 (exported to XML)

Going to start trawling logs but said I'd port here just in case it's something I've missed or been stupid about

**Comment by donalby** [comment]
Following is the log excerpt that I've found for when I try the import:
Issue  in Project:<redacted> gives Error: ["Assignee can't be blank"]
  Rendered plugins/msproject_import/app/views/msproj_imp/analyze.html.erb within layouts/base (2.4ms)
  Rendered inline template (0.7ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (0.6ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (2.2ms)
Completed 200 OK in 4652.5ms (Views: 49.9ms | ActiveRecord: 13.8ms)

**Comment by braini75** [comment]
It seems to me, that you are not allowed to create unassigned issues, right?
Though the Problem is, that the plugin will leave issues unassigned if no matching user ist found.
